#pragma config(Motor,  motorB,          A,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorA,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Sensor, S1,     0,              sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
//#pragma config(Sensor, S4,     3,              sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


float kVelocidade = 2.07;
int us;
int sensor1;
int sensor2;
int sensor3;

task Sensor()
{
	while(true)
	{
		if(sensor3<sensor1 && sensor3<sensor2)
			us = 3;//esquerda
		if(sensor2<sensor3 && sensor2<sensor1)
			us = 2;//direita
	//	if(sensor1<sensor2 && sensor1<sensor3)
	//		us = 1;//centro
	}
}

void Procurar()
{
		sensor3 = SensorValue[2];
		writeDebugStream("%d\n",sensor3);
		sensor1 = SensorValue[0];
		writeDebugStream("%d\n",sensor1);
		sensor2 = SensorValue[1];
		writeDebugStream("%d\n",sensor2);
		while(sensor1>sensor2 && sensor1>sensor3)
		{
			if(us == 3)
			{
				motor[motorB] = 50;
				motor[motorC] = -50;
			}
			if(us == 2)
			{
				motor[motorB] = -50;
				motor[motorC] = 50;
			}
		}
}

void MoveFrente()
{
	motor[motorC] = 100;
	motor[motorB] = 100;
}

task main()
{
	while(true)
	{
		StartTask(Sensor);
		Procurar();
		while(sensor1<sensor2 && sensor1<sensor3)
		{
			MoveFrente();
			if(sensor2<sensor3)
				motor[motorB] = 90;
			if(sensor3<sensor2)
				motor[motorC] = 90;
			/*if(sensor1<30)
			{
				MoveFrente();
				while(nMotorEncoder[motorB] < 45*kVelocidade)
					motor[motorA] = 100;
			}*/
		}
	}
}
