#pragma config(Motor,  motorB,          A,             tmotorNXT, PIDControl, reversed, encoder)//esquerda
#pragma config(Motor,  motorA,          E,             tmotorNXT, PIDControl, reversed, encoder)//rampa
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)//direita
#pragma config(Sensor, S1,     0,              sensorSONAR) //esquerda
#pragma config(Sensor, S2,     1,              sensorSONAR) // meio
#pragma config(Sensor, S3,     2,              sensorSONAR) // direita
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Suponto uma luta ja em andamento apos a execucao da estrategia inicial

float kVelocidade = 2.07;
int us = 2; // ultima posicao detectada direita 2 - esquerda 3
int sensor3 = S3;
int	sensor1 = S1;
int	sensor2 = S2;

task Sensor()
{
	while(true)
	{
		sensor3 = SensorValue[S3];
		writeDebugStream("sensor3 %d\n",sensor3);
		sensor1 = SensorValue[S1];
		writeDebugStream("sensor1 %d\n",sensor1);
		sensor2 = SensorValue[S2];
		writeDebugStream("sensor2 %d\n",sensor2);
	}
}

void abaixarRampa()
{
	nMotorEncoder[motorA] = -50;
	wait10Msec(10);
	nMotorEncoder[motorA] = 0;
}

void Procurar()
{
	if(us == 3)
	{
		while(sensor3>sensor1/* || sensor3>sensor2*/)
		{
			motor[motorB] = -50;
			motor[motorC] = 50;
		}
	}

	if(us == 2)
	{
		while(sensor3>sensor2/* || sensor3>sensor1*/)
		{
			motor[motorB] = 50;
			motor[motorC] = -50;
		}
	}
}

void MoveFrente()
{
	motor[motorC] = 100;
	motor[motorB] = 100;
}

task main()
{
	abaixarRampa();
	while(true)
	{
		nMotorEncoder[motorA] = 0;
		StartTask(Sensor);
		Procurar();
		while(sensor3<sensor1 && sensor3<sensor2)
		{
			MoveFrente();
			if(sensor1<sensor2)
				motor[motorB] = 90;
			if(sensor2<sensor1)
				motor[motorC] = 90;
			if(sensor3<18)
			{
				MoveFrente();
				while(nMotorEncoder[motorA] < 45*kVelocidade)
					motor[motorA] = 50;
			}
		}
	}
}
